const mongoose = require('mongoose');

const studentSchema = new mongoose.Schema({
  fullName: String,
  mobile: String,
  whatsapp: String,
  email: String,
  dob: String,
  gender: String,
  city: String,
  state: String,
  linkedin: String,
  portfolio: String,
  profilePicture: String,
  collegeName: String,
  courseBranch: String,
  collegeLocation: String,
  yearOfPassing: String,
  academicScore: String,
  backlogs: String,
  enrolledCourse: [String],
  trainingMode: String,
  trainer: String,
  batchTime: String,
  startDate: String,
  trainingTime: String,
  fee: String,
  recievedAmount: String,
  paymentStatus: String,
  nextCall: String,
  discussion: String,
  remarks: String,
  resumeStatus: String,
  leadSource: String,
  counselor: String,
  updatedAt: String,
  docsCollected: String,
  interviewStatus: String,
  interviewerName:String,
  interviewDate:String,
  placementStatus: String,
  company: String,
  ctc: String,
  trainingStatus: String,
  
addedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
  
}, { timestamps: true });

module.exports = mongoose.model('Student', studentSchema);
